### ISSUE TITLE
Error using default installation instructions

### ISSUE THREAD

**Issue by dbebawy** [cybercog/laravel-youtrack-sdk#5]
Followed steps in readme and received this error:
`Class Cog\YouTrack\Rest\YouTrackClient does not exist`

**Comment by dbebawy** [comment]
Updated: 
`        $youtrack = app(\Cog\YouTrack\Rest\YouTrackClient::class);`
to:
`        $youtrack = app(\Cog\YouTrack\Rest\Client\YouTrackClient::class);`
and received error:
`  Target [Cog\Contracts\YouTrack\Rest\HttpClient\HttpClient] is not instantiable while building [Cog\YouTrack\Rest\Client\YouTrackClient].`

**Comment by antonkomarev** [comment]
@dbebawy, thank you for reporting! I haven't updated documentation.

You should bypass contract to application container, not concrete implementation:
```php
$client = app(\Cog\Contracts\YouTrack\Rest\Client\Client::class);
```

After then instantiated concrete implementation will be returned:
`\Cog\YouTrack\Rest\Client\YouTrackClient`

![Instantiated YouTrackClient](https://screenshots.firefoxusercontent.com/images/c033e4d6-e3a9-4cc0-8855-c890db1aab0c.png)

Does it help you?

**Comment by dbebawy** [comment]
Yes, Thank you. I was able to instantiate the client.
